---
title: "figure 1 and 2"
author: "Koen Van den Berge"
date: "2/26/2020"
output: html_document
---

```{r}
library(GenomicAlignments)
library(tidyverse)
library(cqn)
library(RColorBrewer)
library(edgeR)
library(ggplot2)
library(cowplot)
library(ggridges)
library(gridExtra)
colsBig <- clusterExperiment:::massivePalette
plotGCHex <- function(gr, counts){
  counts2 <- counts
  df <- as_tibble(cbind(counts2,gc=mcols(gr)$gc))
  df <- gather(df, sample, value, -gc)
  ggplot(data=df, aes(x=gc, y=log(value+1)) ) + 
    ylab("log(count + 1)") + xlab("GC-content") + 
    geom_hex(bins = 50) + theme_bw() #+ facet_wrap(~sample, nrow=2)
}
pal <- RColorBrewer::brewer.pal(n=8, "Dark2")
source("../../methods/gcqn_validated.R")

### this dataset combines samples from a number of different sources, therefore the GC effects are wildly different between samples.
data=read.delim("../../data/calderon2019_GSE118189/GSE118189_ATAC_counts.txt.gz")
colnames(data) <- substr(colnames(data),2,nchar(colnames(data)))

# get GC content
rn <- rownames(data)
sn <- unlist(lapply(lapply(strsplit(rn,split="_"),"[",1),function(x) gsub(pattern="chr",x=x,replacement="")))
start <- as.numeric(unlist(lapply(strsplit(rn,split="_"),"[",2)))
end <- as.numeric(unlist(lapply(strsplit(rn,split="_"),"[",3)))
gr <- GRanges(seqnames=sn, ranges=IRanges(start, end), strand="*", mcols=data.frame(peakID=rn))
ff <- FaFile("~/data/genomes/human/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz")
peakSeqs <- getSeq(x=ff, gr)
gcContentPeaks <- letterFrequency(peakSeqs, "GC",as.prob=TRUE)[,1]
gcGroups <- Hmisc::cut2(gcContentPeaks, g=20)
mcols(gr)$gc <- gcContentPeaks
widthGroups <- Hmisc::cut2(width(gr), g=20)

# get metadata
cnames <- colnames(data)
donor <- unlist(lapply(strsplit(cnames,split=".",fixed=TRUE),"[",1))
celltype <- factor(unlist(lapply(strsplit(cnames,split=".",fixed=TRUE),"[",2)))
condition <- unlist(lapply(strsplit(cnames,split=".",fixed=TRUE),"[",3))
table(celltype,condition)

# QC measures
qcMeasures <- openxlsx::read.xlsx(xlsxFile = "../../data/calderon2019_GSE118189/Supplementary_tables.xlsx",
                    sheet = 5)
qcMeasures <- qcMeasures[,1:4]
qcMeasures$sample <- gsub(x=qcMeasures$sample, pattern="-", replacement=".", fixed=TRUE)
rownames(qcMeasures) <- qcMeasures$sample
qcMeasures <- qcMeasures[colnames(data),]

# batch
addSamples <- read.table("../../data/calderon2019_GSE118189/samples_with_additional_resequencing.txt",
                         stringsAsFactors = FALSE)[,1]
addSamples <- gsub(x=addSamples, pattern="-", replacement=".", fixed=TRUE)
batch2 <- rep(0, ncol(data))
names(batch2) <- colnames(data)
batch2[addSamples]<- 1
batch2 <- factor(batch2)
batch <- droplevels(interaction(donor, batch2))

table(celltype,condition, batch)
counts <- as.matrix(data) ; rm(data) ; gc()

dfGCWidth <- data.frame(gc=gcContentPeaks,
                        width=width(gr))
ggplot(dfGCWidth, aes(x=gc, y=log(width))) +
  geom_hex() +
  geom_smooth(se=FALSE, color="red", aes(group=1), lwd=1)
```


# Lowess fits

## GC content

```{r}

lowListGC <- list()
for(kk in 1:ncol(counts)){
  set.seed(kk)
  lowListGC[[kk]] <- lowess(x=gcContentPeaks, y=log1p(counts[,kk]), f=1/10)
}


for(cc in 1:nlevels(celltype)){
  curCT <- levels(celltype)[cc]
  id <- which(celltype == curCT)
  curBatch <- batch[id]
  plot(x=seq(min(gcContentPeaks), max(gcContentPeaks), length=10),
     y=seq(0, 4, length=10), type='n',
     xlab="GC-content", ylab="log(count + 1)", main=curCT)
  for(ii in 1:length(id)){
    curID <- id[ii]
    oo <- order(lowListGC[[curID]]$x)
    lines(x=lowListGC[[curID]]$x[oo], y=lowListGC[[curID]]$y[oo], col=colsBig[batch[curID]])
  }
}

for(bb in 1:nlevels(batch)){
  curB <- levels(batch)[bb]
  id <- which(batch == curB)
  plot(x=seq(min(gcContentPeaks), max(gcContentPeaks), length=10),
     y=seq(0, 4, length=10), type='n',
     xlab="GC-content", ylab="log(count + 1)", main=curB)
  for(ii in 1:length(id)){
    curID <- id[ii]
    oo <- order(lowListGC[[curID]]$x)
    lines(x=lowListGC[[curID]]$x[oo], y=lowListGC[[curID]]$y[oo], col=colsBig[batch[curID]])
  }
}
```


# Visualization

```{r}
lowMemNK <- lowListGC[celltype == "Memory_NK"]
dfList <- list()
for(ss in 1:length(lowMemNK)){
  oox <- order(lowMemNK[[ss]]$x)
  dfList[[ss]] <- data.frame(x=lowMemNK[[ss]]$x[oox], y=lowMemNK[[ss]]$y[oox], sample=ss)
}
dfAll <- do.call(rbind, dfList)
dfAll$sample <- factor(dfAll$sample)

## association of GC content with counts
plotGCHex(gr, rowMeans(counts[, celltype == "Memory_NK"])) +
  theme(axis.title = element_text(size=16)) +
  labs(fill="Nr. of peaks") + 
  geom_line(aes(x=x, y=y, group=sample, color=sample), data=dfAll, size=1) +
  scale_color_discrete()

## just the average GC content
p1 <- ggplot(dfAll, aes(x=x, y=y, group=sample, color=sample)) +
  geom_line(size = 1) +
  xlab("GC-content") +
  ylab("log(count + 1)") +
  theme_classic()
#  rm(lowListGC) ; gc()

## seq depth
dfLS <- data.frame(sample=1:6,
                   libSize=colSums(counts[, celltype == "Memory_NK"]))
dfLSAll <- merge(dfAll, dfLS, by="sample")
dfLSAll$logLibSize <- log(dfLSAll$libSize)
maxDf <- dfLSAll %>% group_by(sample) %>% summarize(maxX=max(x),
                                                     maxY=max(y))

p1LS <- ggplot(dfLSAll, aes(x=x, y=y, group=sample, color=sample)) +
 # scale_color_gradient(low="yellow", high="red") +
  geom_line(size = 1) +
  xlab("GC-content") +
  ylab("log(count + 1)") +
  theme_classic() +
  annotate(geom="text", x=maxDf$maxX,
           y=dfLSAll[dfLSAll$x == maxDf$maxX[1], "y"], 
           label=round(log(colSums(counts[,celltype == "Memory_NK"])),2),
            color="red")
p1LS
ggsave("../../../../plots/figure1_libSize.pdf")

# across all cell types
set.seed(44)
pList <- c()
id <- sample(nrow(counts), size=1e4)
for(cc in 1:nlevels(celltype)){
  curCT <- levels(celltype)[cc]
  lowCT <- lowListGC[celltype == curCT]
  dfList <- list()
  for(ss in 1:length(lowCT)){
  oox <- order(lowCT[[ss]]$x[id])
  dfList[[ss]] <- data.frame(x=lowCT[[ss]]$x[id][oox], y=lowCT[[ss]]$y[id][oox], sample=ss)
  }
  dfAll <- do.call(rbind, dfList)
  dfAll$sample <- factor(dfAll$sample)
  pCT <- ggplot(dfAll, aes(x=x, y=y, group=sample, color=sample)) +
    geom_line(size = 1) +
    xlab("GC-content") +
    ylab("log(count + 1)") +
    theme_classic() +
    ggtitle(curCT) +
    theme(legend.position = "none") +
    ylim(c(0, 3.5))
  pList[[cc]] <- pCT
}

cowplot::plot_grid(plotlist=pList, nrow=5, ncol=5)

# ggsave("~/Dropbox/research/atacseq/bulk/plots/gcEffectsAllCells.pdf",
#        units="in", width=12, height=9)
# ggsave("~/Dropbox/research/atacseq/bulk/plots/gcEffectsAllCells.png",
#        units="in", width=12, height=9)

rm(lowListGC, lowCT, pList) ; gc()
```

## Peak width

```{r}
lowListWidth <- list()
for(kk in 1:ncol(counts)){
  lowListWidth[[kk]] <- lowess(x=log(width(gr)), y=log1p(counts[,kk]), f=1/10)
}

plot(x=seq(min(log(width(gr))), max(log(width(gr))), length=10),
     y=seq(0, 5, length=10), type='n',
     xlab="GC-content", ylab="log(count + 1)")
for(kk in 1:length(lowListWidth)){
  oo <- order(lowListWidth[[kk]]$x)
  lines(x=lowListWidth[[kk]]$x[oo], y=lowListWidth[[kk]]$y[oo], col=colsBig[kk])
}

# across all cell types
set.seed(44)
pList <- c()
id <- sample(nrow(counts), size=1e4)
for(cc in 1:nlevels(celltype)){
  curCT <- levels(celltype)[cc]
  lowCT <- lowListWidth[celltype == curCT]
  dfList <- list()
  for(ss in 1:length(lowCT)){
  oox <- order(lowCT[[ss]]$x[id])
  dfList[[ss]] <- data.frame(x=lowCT[[ss]]$x[id][oox], y=lowCT[[ss]]$y[id][oox], sample=ss)
  }
  dfAll <- do.call(rbind, dfList)
  dfAll$sample <- factor(dfAll$sample)
  pCT <- ggplot(dfAll, aes(x=x, y=y, group=sample, color=sample)) +
    geom_line(size = 1) +
    xlab("Log peak width") +
    ylab("log(count + 1)") +
    theme_classic() +
    ggtitle(curCT) +
    theme(legend.position = "none") +
    ylim(c(0, 4.5))
  pList[[cc]] <- pCT
}

cowplot::plot_grid(plotlist=pList, nrow=5, ncol=5)

# ggsave("~/Dropbox/research/atacseq/bulk/plots/widthEffectsAllCells.pdf",
#        units="in", width=12, height=9)
# ggsave("~/Dropbox/research/atacseq/bulk/plots/widthEffectsAllCells.png",
#        units="in", width=12, height=9)

rm(lowListWidth) ; gc()
```




# Mock comparisons

```{r}
# Memory_NK cells
memContID <- celltype == "Memory_NK" & condition == "U"
countsMemControl <- counts[,memContID]
keepMemContr <- rowSums(cpm(countsMemControl) >= 2) >=3 
countsMemControl <- countsMemControl[keepMemContr, ]
# these are all from different batches.
table(droplevels(batch[memContID]))
# equally sized bins after filtering
gcGroupsMem <- Hmisc::cut2(gcContentPeaks[keepMemContr], g=20)
gcGroupsMem10 <- Hmisc::cut2(gcContentPeaks[keepMemContr], g=10)
gcMem <- gcContentPeaks[keepMemContr]
widthGroupsMem <- Hmisc::cut2(width(gr)[keepMemContr], g=20)


set.seed(33)
mock <- factor(sample(rep(letters[1:2], each=3)))
design <- model.matrix(~mock)
rownames(design) <- colnames(countsMemControl)
mock
design
head(countsMemControl)
```

## No normalization

```{r}
## TMM normalization
library(edgeR)
d <- DGEList(countsMemControl)
d <- estimateDisp(d, design)
fit <- glmFit(d, design)
lrt <- glmLRT(fit, coef=2) 
dfEdgeR <- data.frame(logFC=log(2^lrt$table$logFC),
                 gc=gcGroupsMem)
pNone <- ggplot(dfEdgeR, aes(x=gc, y=logFC, color=gc)) +
  geom_violin() +
  geom_boxplot(width=0.1) +
  scale_color_manual(values=wesanderson::wes_palette("Zissou1", nlevels(gcGroups), "continuous")) +
  geom_abline(intercept = 0, slope = 0, col="black", lty=2) +
  theme_bw() + 
  ylim(c(-1,1)) +
  ggtitle("No normalization") +
  xlab("GC-content bin") +
  theme(axis.text.x = element_text(angle = 45, vjust = .5),
        legend.position = "none",
        axis.title = element_text(size=16)) +
  geom_smooth(se=FALSE, color="blue", aes(group=1), lwd=1)
pNone


dfEdgeRWidth <- data.frame(logFC=log(2^lrt$table$logFC),
                 peakWidth=widthGroupsMem)

pNoneWidth <- ggplot(dfEdgeRWidth, aes(x=peakWidth, y=logFC, color=peakWidth)) +
  geom_violin() +
  geom_boxplot(width=0.1) +
  scale_color_manual(values=wesanderson::wes_palette("Zissou1", nlevels(dfEdgeRWidth$peakWidth), "continuous")) +
  geom_abline(intercept = 0, slope = 0, col="black", lty=2) +
  theme_bw() + 
  ylim(c(-1,1)) +
  ggtitle("No normalization") +
  xlab("Peak width bin") +
  theme(axis.text.x = element_text(angle = 45, vjust = .5),
        legend.position = "none",
        axis.title = element_text(size=16)) +
  geom_smooth(se=FALSE, color="blue", aes(group=1), lwd=1)
pNoneWidth

```


## edgeR (TMM normalization)

```{r}
## TMM normalization
library(edgeR)
d <- DGEList(countsMemControl)
d <- calcNormFactors(d)
d <- estimateDisp(d, design)
fit <- glmFit(d, design)
lrt <- glmLRT(fit, coef=2) 
dfEdgeR <- data.frame(logFC=log(2^lrt$table$logFC),
                 gc=gcGroupsMem)
pedgeR <- ggplot(dfEdgeR, aes(x=gc, y=logFC, color=gc)) +
  geom_violin() +
  geom_boxplot(width=0.1) +
  scale_color_manual(values=wesanderson::wes_palette("Zissou1", nlevels(gcGroups), "continuous")) +
  geom_abline(intercept = 0, slope = 0, col="black", lty=2) +
  theme_bw() + 
  ylim(c(-1,1)) +
  ggtitle("TMM normalization") +
  xlab("GC-content bin") +
  theme(axis.text.x = element_text(angle = 45, vjust = .5),
        legend.position = "none",
        axis.title = element_text(size=16)) +
  geom_smooth(se=FALSE, color="blue", aes(group=1), lwd=1)
pedgeR


dfEdgeRWidth <- data.frame(logFC=log(2^lrt$table$logFC),
                 peakWidth=widthGroupsMem)

pedgeRWidth <- ggplot(dfEdgeRWidth, aes(x=peakWidth, y=logFC, color=peakWidth)) +
  geom_violin() +
  geom_boxplot(width=0.1) +
  scale_color_manual(values=wesanderson::wes_palette("Zissou1", nlevels(dfEdgeRWidth$peakWidth), "continuous")) +
  geom_abline(intercept = 0, slope = 0, col="black", lty=2) +
  theme_bw() + 
  ylim(c(-1,1)) +
  ggtitle("TMM normalization") +
  xlab("Peak width bin") +
  theme(axis.text.x = element_text(angle = 45, vjust = .5),
        legend.position = "none",
        axis.title = element_text(size=16)) +
  geom_smooth(se=FALSE, color="blue", aes(group=1), lwd=1)
pedgeRWidth

```

## DESeq2 (MOR normalization)

```{r}
## DESeq2 normalization
library(DESeq2)
dds <- DESeqDataSetFromMatrix(countsMemControl, 
                       colData=data.frame(mock=mock), 
                       design=~mock)
dds <- DESeq(dds)
res <- results(dds, name="mock_b_vs_a")
dfDESeq2 <- data.frame(logFC=log(2^res$log2FoldChange),
                       gc=gcGroupsMem)
pdeseq <- ggplot(dfDESeq2) +
  aes(x=gc, y=logFC, color=gc) +
  geom_violin() +
  geom_boxplot(width=0.1) +
  scale_color_manual(values=wesanderson::wes_palette("Zissou1", nlevels(gcGroups), "continuous")) +
  geom_abline(intercept = 0, slope = 0, col="black", lty=2) +
  theme_bw() + 
  ylim(c(-1,1)) +
  ggtitle("DESeq2 MOR normalization") +
  xlab("GC-content bin") +
  theme(axis.text.x = element_text(angle = 45, vjust = .5),
        legend.position = "none",
        axis.title = element_text(size=16)) +
  geom_smooth(se=FALSE, color="blue", aes(group=1), lwd=1)
pdeseq

dfDESeq2Width <- data.frame(logFC=log(2^res$log2FoldChange),
                 peakWidth=widthGroupsMem)

pdeseqWidth <- ggplot(dfDESeq2Width, aes(x=peakWidth, y=logFC, color=peakWidth)) +
  geom_violin() +
  geom_boxplot(width=0.1) +
  scale_color_manual(values=wesanderson::wes_palette("Zissou1", nlevels(dfDESeq2Width$peakWidth), "continuous")) +
  geom_abline(intercept = 0, slope = 0, col="black", lty=2) +
  theme_bw() + 
  ylim(c(-1,1)) +
  ggtitle("DESeq2 MOR normalization") +
  xlab("Peak width bin") +
  theme(axis.text.x = element_text(angle = 45, vjust = .5),
        legend.position = "none",
        axis.title = element_text(size=16)) +
  geom_smooth(se=FALSE, color="blue", aes(group=1), lwd=1)
pdeseqWidth

```

## Full quantile

```{r}
## Full quantile normalization
countsFQ <- FQnorm(countsMemControl, type="median")
d <- DGEList(countsFQ)
d <- estimateDisp(d, design)
fit <- glmFit(d, design)
lrtFQ <- glmLRT(fit, coef=2) 
dfFQ <- data.frame(logFC=log(2^lrtFQ$table$logFC),
                      gc=gcGroupsMem)
pFQ <- ggplot(dfFQ) +
  aes(x=gc, y=logFC, color=gc) +
  geom_violin() +
  geom_boxplot(width=0.1) +
  scale_color_manual(values=wesanderson::wes_palette("Zissou1", nlevels(gcGroups), "continuous")) +
  geom_abline(intercept = 0, slope = 0, col="black", lty=2) +
  theme_bw() + 
  ylim(c(-1,1)) +
  ggtitle("FQ normalization") +
  xlab("GC-content bin") +
  theme(axis.text.x = element_text(angle = 45, vjust = .5),
        legend.position = "none",
        axis.title = element_text(size=16)) +
  geom_smooth(se=FALSE, color="blue", aes(group=1), lwd=1)
pFQ

dfFQWidth <- data.frame(logFC=log(2^lrtFQ$table$logFC),
                 peakWidth=widthGroupsMem)

pFQWidth <- ggplot(dfFQWidth, aes(x=peakWidth, y=logFC, color=peakWidth)) +
  geom_violin() +
  geom_boxplot(width=0.1) +
  scale_color_manual(values=wesanderson::wes_palette("Zissou1", nlevels(dfFQWidth$peakWidth), "continuous")) +
  geom_abline(intercept = 0, slope = 0, col="black", lty=2) +
  theme_bw() + 
  ylim(c(-1,1)) +
  ggtitle("FQ normalization") +
  xlab("Peak width bin") +
  theme(axis.text.x = element_text(angle = 45, vjust = .5),
        legend.position = "none",
        axis.title = element_text(size=16)) +
  geom_smooth(se=FALSE, color="blue", aes(group=1), lwd=1)
pFQWidth

```


# Composite plot for figure 1

```{r}
p <- plot_grid(p1 + ggtitle("Memory NK cells"), pedgeR, 
               pdeseq, pFQ,
               labels=letters[1:4])
p
# ggsave("~/Dropbox/research/atacseq/bulk/plots/figure1.png",
#        units="in", width=12, height=9)

pWidth <- plot_grid(pedgeRWidth, 
               pdeseqWidth, pFQWidth,
               labels=letters[1:3], 
               ncol=1)
pWidth
# ggsave("~/Dropbox/research/atacseq/bulk/plots/figure1Width.png",
#        units="in", width=9, height=10)
```


# Composite plot for figure 1, including technical/biological GC origin

## Liu

```{r}
## liu
lrtTableListLiver <- readRDS("../../objects/technicalGC/liu_lrtTableListLiver.rds")
lrtTableListHeart <- readRDS("../../objects/technicalGC/liu_lrtTableListHeart.rds")
# remove duplicate comparisons
lrtTableListLiver <- lrtTableListLiver[4:6]
lrtTableListHeart <- lrtTableListHeart[4:6]
lrtBioLiu <- readRDS("../../objects/technicalGC/liu_lrtBio.rds")
gcContentLiu <- readRDS("../../objects/technicalGC/liu_gcContentPeaks.rds")

for(ii in 1:length(lrtTableListHeart)){
  par(bty='l')
  curLowess <- lowess(x=gcContentLiu, y=lrtTableListHeart[[ii]]$logFC, f=1/5)
  oo <- order(curLowess$x)
  if(ii == 1){
    heartDf <- data.frame(x=curLowess$x[oo],
                          y=curLowess$y[oo],
                          replicate=ii)
  } else {
    heartDf <- rbind(heartDf,
                     data.frame(x=curLowess$x[oo],
                          y=curLowess$y[oo],
                          replicate=ii))
  }
}

for(ii in 1:length(lrtTableListLiver)){
  par(bty='l')
  curLowess <- lowess(x=gcContentLiu, y=lrtTableListLiver[[ii]]$logFC, f=1/5)
  oo <- order(curLowess$x)
  if(ii == 1){
    liverDf <- data.frame(x=curLowess$x[oo],
                          y=curLowess$y[oo],
                          replicate=ii + max(heartDf$replicate))
  } else {
    liverDf <- rbind(liverDf,
                     data.frame(x=curLowess$x[oo],
                          y=curLowess$y[oo],
                          replicate=ii + max(heartDf$replicate)))
  }
}

technicalDf <- rbind(heartDf, liverDf)


lowessBio <- lowess(x=gcContentLiu, y=lrtBioLiu$table$logFC, f=1/10)
oo <- order(lowessBio$x)
allDf <- rbind(technicalDf,
               data.frame(x=lowessBio$x[oo],
                          y=lowessBio$y[oo],
                          replicate=ii + max(technicalDf$replicate)))
allDf$type <- factor(ifelse(allDf$replicate < max(allDf$replicate), "Within-group\n(technical)", "Between-group\n(biological)"))

pLiu <- ggplot(allDf, aes(x=x, y=y, group=replicate, col=type)) +
  theme_classic() +
  geom_line() +
  xlab("GC-content") +
  ylab("Log2-fold-change") +
  guides(col=guide_legend(title="Comparison")) +
  geom_hline(yintercept=0)
  #theme(legend.title = element_text("Comparison"))
pLiu
```

## Torre-Ubieta

```{r}
lrtTableListCP <- readRDS("../../objects/technicalGC/torreUbieta_lrtTableListCP.rds")
lrtTableListGZ <- readRDS("../../objects/technicalGC/torreUbieta_lrtTableListGZ.rds")
# remove dup comparisons
lrtTableListGZ <- lrtTableListGZ[1:3]
lrtBioTU <- readRDS("../../objects/technicalGC/torreUbieta_lrtBio.rds")
gcContentTU <- readRDS("../../objects/technicalGC/torreUbieta_gcContentPeaks.rds")

for(ii in 1:length(lrtTableListCP)){
  par(bty='l')
  curLowess <- lowess(x=gcContentTU, y=lrtTableListCP[[ii]]$logFC, f=1/5)
  oo <- order(curLowess$x)
  if(ii == 1){
    cpDf <- data.frame(x=curLowess$x[oo],
                          y=curLowess$y[oo],
                          replicate=ii)
  } else {
    cpDf <- rbind(cpDf,
                     data.frame(x=curLowess$x[oo],
                          y=curLowess$y[oo],
                          replicate=ii))
  }
}

for(ii in 1:length(lrtTableListGZ)){
  par(bty='l')
  curLowess <- lowess(x=gcContentTU, y=lrtTableListGZ[[ii]]$logFC, f=1/5)
  oo <- order(curLowess$x)
  if(ii == 1){
    gzDf <- data.frame(x=curLowess$x[oo],
                          y=curLowess$y[oo],
                          replicate=ii + max(heartDf$replicate))
  } else {
    gzDf <- rbind(gzDf,
                     data.frame(x=curLowess$x[oo],
                          y=curLowess$y[oo],
                          replicate=ii + max(heartDf$replicate)))
  }
}

technicalDf <- rbind(cpDf, gzDf)


lowessBio <- lowess(x=gcContentTU, y=lrtBioTU$table$logFC, f=1/10)
oo <- order(lowessBio$x)
allDf <- rbind(technicalDf,
               data.frame(x=lowessBio$x[oo],
                          y=lowessBio$y[oo],
                          replicate=ii + max(technicalDf$replicate)))
allDf$type <- factor(ifelse(allDf$replicate < max(allDf$replicate), "Within-group\n(technical)", "Between-group\n(biological)"))

pTorre <- ggplot(allDf, aes(x=x, y=y, group=replicate, col=type)) +
  theme_classic() +
  geom_line() +
  xlab("GC-content") +
  ylab("Log2-fold-change") +
  guides(col=guide_legend(title="Comparison")) +
  geom_hline(yintercept=0)
  #theme(legend.title = element_text("Comparison"))
pTorre

```

## Composite figure

```{r}
pTech <- cowplot::plot_grid(pLiu + theme(legend.position="none") , 
                            pTorre, 
                            nrow=1, labels=letters[5:6], rel_widths=c(.43,.57))
pTech
pFig1All <- cowplot::plot_grid(p, pTech, nrow=2, rel_heights = c(2/3, 1/3))
pFig1All
ggsave("~/Dropbox/research/atacseq/bulk/plots/figure1_extended.png",
       units="in", width=12, height=9)
```



# Figure 2

```{r}

##### FIGURE 2
## cqn
cqnModel <- cqn(countsMemControl, x=gcMem, sizeFactors = colSums(countsMemControl),
                lengths=width(gr)[keepMemContr])
d <- DGEList(countsMemControl)
d$offset <- cqnModel$glm.offset
d <- estimateDisp(d, design)
fit <- glmFit(d, design)
lrtCqn <- glmLRT(fit, coef=2)
dfCqn <- data.frame(logFC=log(2^lrtCqn$table$logFC),
                   gc=gcGroupsMem)
pCqn <- ggplot(dfCqn) +
  aes(x=gc, y=logFC, color=gc) +
  geom_violin() +
  geom_boxplot(width=0.1) +
  scale_color_manual(values=wesanderson::wes_palette("Zissou1", nlevels(gcGroups), "continuous")) +
  geom_abline(intercept = 0, slope = 0, col="black", lty=2) +
  theme_bw() + 
  ylim(c(-1,1)) +
  xlab("GC-content bin") +
  ggtitle("cqn normalization") +
  theme(axis.text.x = element_text(angle = 45, vjust = .5),
        legend.position = "none",
        axis.title = element_text(size=16)) +
  geom_smooth(se=FALSE, color="blue", aes(group=1), lwd=1)
pCqn

dfCqnWidth <- data.frame(logFC=log(2^lrtCqn$table$logFC),
                   peakWidth=widthGroupsMem)
pCqnWidth <- ggplot(dfCqnWidth, aes(x=peakWidth, y=logFC, color=peakWidth)) +
  geom_violin() +
  geom_boxplot(width=0.1) +
  scale_color_manual(values=wesanderson::wes_palette("Zissou1", nlevels(dfCqnWidth$peakWidth), "continuous")) +
  geom_abline(intercept = 0, slope = 0, col="black", lty=2) +
  theme_bw() + 
  ylim(c(-1,1)) +
  xlab("Peak width bin") +
  ggtitle("cqn normalization") +
  theme(axis.text.x = element_text(angle = 45, vjust = .5),
        legend.position = "none",
        axis.title = element_text(size=16)) +
  geom_smooth(se=FALSE, color="blue", aes(group=1), lwd=1)
pCqnWidth

# ## EDASeq
library(EDASeq)
#emptyRows <- which(rownames(countsMouse) == "")
#rownames(countsMouse)[emptyRows] <- paste0("emptyPeak",1:length(emptyRows))
dataWithin <- withinLaneNormalization(countsMemControl, y=gcMem,
                                      num.bins=20, which="full")
dataNorm <- betweenLaneNormalization(dataWithin, which="full")
d <- DGEList(dataNorm)
d <- estimateDisp(d, design)
fit <- glmFit(d, design)
lrtEDASeq <- glmLRT(fit, coef=2)
dfEDASeq <- data.frame(logFC=log(2^lrtEDASeq$table$logFC),
                    gc=gcGroupsMem)
pEDASeq <- ggplot(dfEDASeq) +
  aes(x=gc, y=logFC, color=gc) +
  geom_violin() +
  geom_boxplot(width=0.1) +
  scale_color_manual(values=wesanderson::wes_palette("Zissou1", nlevels(gcGroups), "continuous")) +
  geom_abline(intercept = 0, slope = 0, col="black", lty=2) +
  theme_bw() +
  ylim(c(-1,1)) +
  xlab("GC-content bin") +
  ggtitle("FQ-FQ normalization") +
  theme(axis.text.x = element_text(angle = 45, vjust = .5),
        legend.position = "none",
        axis.title = element_text(size=16)) +
  geom_smooth(se=FALSE, color="blue", aes(group=1), lwd=1)
pEDASeq

dfEDASeqWidth <- data.frame(logFC=log(2^lrtEDASeq$table$logFC),
                   peakWidth=widthGroupsMem)
pEDASeqWidth <- ggplot(dfEDASeqWidth, aes(x=peakWidth, y=logFC, color=peakWidth)) +
  geom_violin() +
  geom_boxplot(width=0.1) +
  scale_color_manual(values=wesanderson::wes_palette("Zissou1", nlevels(dfCqnWidth$peakWidth), "continuous")) +
  geom_abline(intercept = 0, slope = 0, col="black", lty=2) +
  theme_bw() + 
  ylim(c(-1,1)) +
  xlab("Peak width bin") +
  ggtitle("FQ-FQ normalization") +
  theme(axis.text.x = element_text(angle = 45, vjust = .5),
        legend.position = "none",
        axis.title = element_text(size=16)) +
  geom_smooth(se=FALSE, color="blue", aes(group=1), lwd=1)
pEDASeqWidth


## GC-QN
countsGCQN <- gcqn(countsMemControl, gcGroupsMem, summary = "median")
d <- DGEList(countsGCQN)
d <- estimateDisp(d, design)
fit <- glmFit(d, design)
lrtGCQN <- glmLRT(fit, coef=2)
dfGCQN <- data.frame(logFC=log(2^lrtGCQN$table$logFC),
                   gc=gcGroupsMem)
pGCQN <- ggplot(dfGCQN) +
  aes(x=gc, y=logFC, color=gc) +
  geom_violin() +
  geom_boxplot(width=0.1) +
  scale_color_manual(values=wesanderson::wes_palette("Zissou1", nlevels(gcGroups), "continuous")) +
  geom_abline(intercept = 0, slope = 0, col="black", lty=2) +
  theme_bw() + 
  ylim(c(-1,1)) +
  xlab("GC-content bin") +
  ggtitle("GC-FQ normalization") +
  theme(axis.text.x = element_text(angle = 45, vjust = .5),
        legend.position = "none",
        axis.title = element_text(size=16)) +
  geom_smooth(se=FALSE, color="blue", aes(group=1), lwd=1)
pGCQN

dfGCQNWidth <- data.frame(logFC=log(2^lrtGCQN$table$logFC),
                   peakWidth=widthGroupsMem)
pGCQNWidth <- ggplot(dfGCQNWidth, aes(x=peakWidth, y=logFC, color=peakWidth)) +
  geom_violin() +
  geom_boxplot(width=0.1) +
  scale_color_manual(values=wesanderson::wes_palette("Zissou1", nlevels(dfCqnWidth$peakWidth), "continuous")) +
  geom_abline(intercept = 0, slope = 0, col="black", lty=2) +
  theme_bw() + 
  ylim(c(-1,1)) +
  xlab("Peak width bin") +
  ggtitle("GC-FQ normalization") +
  theme(axis.text.x = element_text(angle = 45, vjust = .5),
        legend.position = "none",
        axis.title = element_text(size=16)) +
  geom_smooth(se=FALSE, color="blue", aes(group=1), lwd=1)
pGCQNWidth

## ridges plot before normalization
countsN <- countsMemControl[,order(colSums(countsMemControl), decreasing=TRUE)[1:3]]


lc <- log1p(c(countsN))
joyDat <- data.frame(lc=lc, 
                     gc=rep(gcGroupsMem10, 3),
                     sample=rep(1:3, each=nrow(countsN)))
axText <- 0
pRidge1 <- joyDat %>% ggplot(aes(y=gc)) + 
  geom_density_ridges(aes(x=lc)) + 
  facet_wrap(.~sample) +
  theme_ridges(grid=FALSE, font_size=5, center_axis_labels = TRUE) + 
  xlim(c(0.5,7)) +
  xlab("log(count + 1)") +
  ylab("GC-content bin") +
  theme(axis.text.y = element_text(size=axText),
        axis.text.x = element_text(size=10),
        legend.position = "none",
        axis.title = element_text(size=16), 
             strip.background = element_blank(),
             strip.text.x = element_blank())

pFC <- cowplot::plot_grid(pCqn, pEDASeq, pGCQN,
                          labels=letters[2:4],
                          nrow=3, ncol=1)

pFig2 <- cowplot::plot_grid(pRidge1, 
                   pFC,
                   labels=c("a",""))
pFig2
# ggsave("~/Dropbox/research/atacseq/bulk/plots/figure2.png",
#        units="in", width=12, height=9)

pWidth2 <- cowplot::plot_grid(pCqnWidth, pEDASeqWidth, pGCQNWidth,
                          labels=letters[1:3],
                          nrow=3, ncol=1)
pWidth2
ggsave("~/Dropbox/research/atacseq/bulk/plots/figure2Width.png",
       units="in", width=9, height=10)
```





