---
title: "Calderon simulation results"
author: "Koen Van den Berge"
date: "7/28/2020"
output: html_document
---


```{r}
library(iCOBRA)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(cowplot)


theme_set(theme_bw())
theme_update(legend.position = "none",
             panel.grid.major.y = element_blank(),
             panel.grid.minor.y = element_blank(),
             panel.grid.major.x = element_line(linetype = "dashed", colour = "black"),
             panel.grid.minor.x = element_line(linetype = "dashed", colour = "grey"),
             axis.title.x = element_text(size = rel(1)),
             axis.title.y = element_text(size = rel(1)),
             axis.text.x = element_text(size = rel(.8)),
             axis.text.y = element_text(size = rel(.8)))


resFiles <- list.files(".",pattern="simRes*")
methods2 <- c("cqn","DESeq2", "FQ-FQ","FQ", "GC-FQ", "GC-FQ_smooth", "qsmooth", "RUVg", "TMM" )
cols2 <-  c("#4292C6", "#4daf4a", "#e41a1c", "#e78ac3", "#ff7f00", "gold", "darkgoldenrod1", "salmon", "darkseagreen3", "darkolivegreen")
names(cols2) <- methods2


pMeanList <- list()
for(ii in 1:length(resFiles)){
  cobraList <- readRDS(resFiles[ii])
  curN <- as.numeric(substr(strsplit(resFiles[ii], split="_")[[1]][2],
                            start=2,stop=3))
  curDE <- as.numeric(substr(strsplit(resFiles[ii], split="_")[[1]][3],start=4,stop=4))
  if(curDE == 1) curDE = "10% DA"
  if(curDE == 2) curDE = "25% DA"
  iter <- 0
  dfList <- lapply(cobraList, function(cobra){
    iter <<- iter+1
    pvals <- pval(cobra)
    truths <- as.logical(truth(cobra)[,1])
    # performance for all p-value based methods
    hlp <- apply(pvals,2,function(x){
      pOrder <- order(x,decreasing=FALSE)
      padj <- p.adjust(x,"fdr")
      fdr <- cumsum(!truths[pOrder])/(1:length(pOrder))
      tpr <- cumsum(truths[pOrder])/sum(truths)
      df <- data.frame(fdr=fdr, tpr=tpr, cutoff=(1:length(padj))/length(padj))
    })
    # summarize
    dfIter <- do.call(rbind,hlp)
    dfIter$method=rep(colnames(pvals),each=nrow(pvals))
    dfIter$iter <- iter
    return(dfIter)
  })
  df <- as_tibble(do.call(rbind,dfList))
  df <- df %>% group_by(method,cutoff) %>%
          summarize(meanTPR=mean(tpr,na.rm=TRUE),
                  meanFDR=mean(fdr,na.rm=TRUE))
  df$method[df$method == "edaseq"] <- "FQ-FQ"
  df$method[df$method == "gcqn"] <- "GC-FQ"
  df$method[df$method == "gcqn_smooth"] <- "GC-FQ_smooth"
  fdrWorkingPointId <- df %>% group_by(method) %>% summarize(nmin = which.min(abs(cutoff-0.05)))
  rowID <- unique(fdrWorkingPointId$nmin)
  if(length(rowID) > 1) stop("Can't do nominal FDR working points.")
  fdrWorkingPoints <- df %>% group_by(method) %>% filter(., row_number() == rowID)
  pMeanAll <- ggplot(df, aes(x=meanFDR, y=meanTPR, col=method)) + 
    geom_path(size = 1) +
    scale_x_continuous(limits = c(0, 1), breaks = c(0.01, 0.05, 0.1, 0.5, 1),
                     minor_breaks = c(0:5) * .1) +
    scale_y_continuous(limits = c(0, 1)) +
    scale_color_manual(values = cols2, breaks = names(cols2)) +
    ggtitle(paste0("n=",curN,", ",curDE)) + 
    guides(col=guide_legend(nrow=2)) + 
    xlab("FDR") + 
    ylab("TPR") +
    coord_fixed() +
    geom_point(data=fdrWorkingPoints, aes(x=meanFDR, y=meanTPR, col=method), size=2) +
    geom_point(data=fdrWorkingPoints, aes(x=meanFDR, y=meanTPR), size=1, col="white") 
    
  if(ii == 1){
    leg <- get_legend(pMeanAll + labs(col = "", linetype = "") +
                             theme(legend.position = "bottom",
                                   legend.key.width = unit(1.3, "cm")))
  }
  pMeanList[[ii]] <- pMeanAll
}

p1 <- cowplot::plot_grid(plotlist=pMeanList, nrow=4, ncol=2, scale=1.05)
p2 <- cowplot::plot_grid(p1, leg, nrow=2, rel_heights=c(0.9,0.1))
p2
ggsave("meanPerformanceCurves.pdf", width = unit(9, "in"), height = unit(13, "in"), scale = .7)

```


## Zoomed in

```{r}
pMeanListZoom <- list()
for(ii in 1:length(resFiles)){
  cobraList <- readRDS(resFiles[ii])
  curN <- as.numeric(substr(strsplit(resFiles[ii], split="_")[[1]][2],
                            start=2,stop=3))
  curDE <- as.numeric(substr(strsplit(resFiles[ii], split="_")[[1]][3],start=4,stop=4))
  if(curDE == 1) curDE = "10% DA"
  if(curDE == 2) curDE = "25% DA"
  iter <- 0
  dfList <- lapply(cobraList, function(cobra){
    iter <<- iter+1
    pvals <- pval(cobra)
    truths <- as.logical(truth(cobra)[,1])
    # performance for all p-value based methods
    hlp <- apply(pvals,2,function(x){
      pOrder <- order(x,decreasing=FALSE)
      padj <- p.adjust(x,"fdr")
      fdr <- cumsum(!truths[pOrder])/(1:length(pOrder))
      tpr <- cumsum(truths[pOrder])/sum(truths)
      df <- data.frame(fdr=fdr, tpr=tpr, cutoff=(1:length(padj))/length(padj))
    })
    # summarize
    dfIter <- do.call(rbind,hlp)
    dfIter$method=rep(colnames(pvals),each=nrow(pvals))
    dfIter$iter <- iter
    return(dfIter)
  })
  df <- as_tibble(do.call(rbind,dfList))
  df <- df %>% group_by(method,cutoff) %>%
          summarize(meanTPR=mean(tpr,na.rm=TRUE),
                  meanFDR=mean(fdr,na.rm=TRUE))
  df$method[df$method == "edaseq"] <- "FQ-FQ"
  df$method[df$method == "gcqn"] <- "GC-FQ"
  df$method[df$method == "gcqn_smooth"] <- "GC-FQ_smooth"
  fdrWorkingPointId <- df %>% group_by(method) %>% summarize(nmin = which.min(abs(cutoff-0.05)))
  rowID <- unique(fdrWorkingPointId$nmin)
  if(length(rowID) > 1) stop("Can't do nominal FDR working points.")
  fdrWorkingPoints <- df %>% group_by(method) %>% filter(., row_number() == rowID)
  pMeanAll <- ggplot(df, aes(x=meanFDR, y=meanTPR, col=method)) + 
    geom_path(size = 1) +
    scale_x_continuous(limits = c(0, 0.5), breaks = c(0.01, 0.05, 0.1, 0.5, 1),
                     minor_breaks = c(0:5) * .1) +
    scale_y_continuous(limits = c(0.2, 0.85)) +
    scale_color_manual(values = cols2, breaks = names(cols2)) +
    ggtitle(paste0("n=",curN,", ",curDE)) + 
    guides(col=guide_legend(nrow=2)) + 
    xlab("FDR") + 
    ylab("TPR") +
    coord_fixed() +
    geom_point(data=fdrWorkingPoints, aes(x=meanFDR, y=meanTPR, col=method), size=2) +
    geom_point(data=fdrWorkingPoints, aes(x=meanFDR, y=meanTPR), size=1, col="white") 
    
  if(ii == 1){
    leg <- get_legend(pMeanAll + labs(col = "", linetype = "") +
                             theme(legend.position = "bottom",
                                   legend.key.width = unit(1.3, "cm")))
  }
  
  pMeanListZoom[[ii]] <- pMeanAll
}

p1Zoom <- cowplot::plot_grid(plotlist=pMeanListZoom, nrow=4, ncol=2, scale=1.05)
p2Zoom <- cowplot::plot_grid(p1Zoom, leg, nrow=2, rel_heights=c(0.9,0.1))
p2Zoom
ggsave("meanPerformanceCurves_zoom.pdf", width = unit(12, "in"), height = unit(9, "in"), scale = .7)

```


## Zoomed in, no aspect ratio

```{r}
pMeanListZoom <- list()
for(ii in 1:length(resFiles)){
  cobraList <- readRDS(resFiles[ii])
  curN <- as.numeric(substr(strsplit(resFiles[ii], split="_")[[1]][2],
                            start=2,stop=3))
  curDE <- as.numeric(substr(strsplit(resFiles[ii], split="_")[[1]][3],start=4,stop=4))
  if(curDE == 1) curDE = "10% DA"
  if(curDE == 2) curDE = "25% DA"
  iter <- 0
  dfList <- lapply(cobraList, function(cobra){
    iter <<- iter+1
    pvals <- pval(cobra)
    truths <- as.logical(truth(cobra)[,1])
    # performance for all p-value based methods
    hlp <- apply(pvals,2,function(x){
      pOrder <- order(x,decreasing=FALSE)
      padj <- p.adjust(x,"fdr")
      fdr <- cumsum(!truths[pOrder])/(1:length(pOrder))
      tpr <- cumsum(truths[pOrder])/sum(truths)
      df <- data.frame(fdr=fdr, tpr=tpr, cutoff=(1:length(padj))/length(padj))
    })
    # summarize
    dfIter <- do.call(rbind,hlp)
    dfIter$method=rep(colnames(pvals),each=nrow(pvals))
    dfIter$iter <- iter
    return(dfIter)
  })
  df <- as_tibble(do.call(rbind,dfList))
  df <- df %>% group_by(method,cutoff) %>%
          summarize(meanTPR=mean(tpr,na.rm=TRUE),
                  meanFDR=mean(fdr,na.rm=TRUE))
  df$method[df$method == "edaseq"] <- "FQ-FQ"
  df$method[df$method == "gcqn"] <- "GC-FQ"
  df$method[df$method == "gcqn_smooth"] <- "GC-FQ_smooth"
  # fdrWorkingPointId <- df %>% group_by(method) %>% summarize(nmin = which.min(abs(cutoff-0.05)))
  # rowID <- unique(fdrWorkingPointId$nmin)
  # if(length(rowID) > 1) stop("Can't do nominal FDR working points.")
  # fdrWorkingPoints <- df %>% group_by(method) %>% filter(., row_number() == rowID)
  pMeanAll <- ggplot(df, aes(x=meanFDR, y=meanTPR, col=method)) + 
    geom_path(size = 4/5) +
    scale_x_continuous(limits = c(0, 0.25), breaks = c(0.01, 0.05, 0.1, 0.5, 1),
                     minor_breaks = c(0:5) * .1) +
    scale_y_continuous(limits = c(0, 0.95)) +
    scale_color_manual(values = cols2, breaks = names(cols2)) +
    ggtitle(paste0("n=",curN,", ",curDE)) + 
    guides(col=guide_legend(nrow=2)) + 
    xlab("FDR") + 
    ylab("TPR") 
    #coord_fixed() +
    # geom_point(data=fdrWorkingPoints, aes(x=meanFDR, y=meanTPR, col=method), size=2) +
    # geom_point(data=fdrWorkingPoints, aes(x=meanFDR, y=meanTPR), size=1, col="white") 
    if(ii %in% c(1)){
      pMeanAll <- pMeanAll + ylim(c(0,0.25)) + xlim(c(0,0.2))
    } else if(ii %in% c(2)){
      pMeanAll <- pMeanAll + ylim(c(0,0.5)) + xlim(c(0,0.2))
    } else if(ii %in% c(3)){
      pMeanAll <- pMeanAll + ylim(c(0.35,0.75)) + xlim(c(0,0.2))
    } else if(ii %in% c(4)){
      pMeanAll <- pMeanAll + ylim(c(0.5,0.9)) + xlim(c(0,0.2))
    } else if(ii %in% c(5)){
      pMeanAll <- pMeanAll + ylim(c(0.65,0.9)) + xlim(c(0,0.15))
    } else if(ii %in% c(6, 7, 8)){
      pMeanAll <- pMeanAll + ylim(c(0.75,.95)) + xlim(c(0,0.1))
    }
  if(ii ==1 ){
    leg <- get_legend(pMeanAll + labs(col = "", linetype = "") +
                             theme(legend.position = "bottom",
                                   legend.key.width = unit(1.3, "cm")))
  }
  
  pMeanListZoom[[ii]] <- pMeanAll
}

p1Zoom <- cowplot::plot_grid(plotlist=pMeanListZoom, nrow=4, ncol=2, scale=1)
p2Zoom <- cowplot::plot_grid(p1Zoom, leg, nrow=2, rel_heights=c(0.9,0.1))
p2Zoom
ggsave("meanPerformanceCurves_zoom_noAR_thinLine.pdf", width = unit(9, "in"), height = unit(12, "in"), scale = .7)

```



```{r, eval=FALSE}
library(iCOBRA)
library(tidyverse)
library(ggplot2)



aucROC <- function(cbd){
  aucVals <- roc(cbd) %>% dplyr::group_by(method) %>% 
    dplyr::mutate(FPR = c(0, FPR[-1])) %>%
    dplyr::mutate(dFPR = c(0, diff(FPR)),
                  dTPR = c(0, diff(TPR)),
                  TPRs = c(0, TPR[-length(TPR)])) %>%
    dplyr::mutate(AUC = cumsum(dFPR * dTPR/2 + dFPR * TPRs),
                  AUCflat = cumsum(dFPR * TPRs)) %>%
    summarize(maxAUC=max(AUC))
  return(aucVals)
}
aucFDRTPR <- function(cbd){
  aucVals <- fdrtprcurve(cbd) %>% dplyr::group_by(method) %>% 
    dplyr::mutate(FDR = c(0, FDR[-1])) %>%
    dplyr::mutate(dFDR = c(0, diff(FDR)),
                  dTPR = c(0, diff(TPR)),
                  TPRs = c(0, TPR[-length(TPR)])) %>%
    dplyr::mutate(AUC = cumsum(dFDR * dTPR/2 + dFDR * TPRs),
                  AUCflat = cumsum(dFDR * TPRs)) %>%
    summarize(maxAUC=max(AUC))
  return(aucVals)
}
# FDR control
getFDR <- function(cbd){
  fdrtpr(cbd) %>% 
    group_by(method) %>% 
    filter(thr == "thr0.05") %>% 
    select(method, FDR)
}

getSummaries <- function(resFile){
  res <- readRDS(resFile)
  # get CBD
  cbdList <- lapply(res, function(x) x$cbd)
  rm(res) ; gc()
  aucDf <- do.call(rbind,lapply(cbdList, aucROC))
  aucFDRDf <- do.call(rbind,lapply(cbdList, aucFDRTPR))
  fdrDf <- do.call(rbind,lapply(cbdList, getFDR))
  return(list(aucROC=aucDf,
              aucFDR=aucFDRDf,
              fdr=fdrDf))
}


resFiles <- list.files(".",pattern="simRes*")
for(ff in 1:length(resFiles)){
  message(ff)
  curFile <- resFiles[ff]
  curN <- as.numeric(substr(strsplit(curFile, split="_")[[1]][2],
                            start=2,stop=3))
  curDE <- as.numeric(substr(strsplit(curFile, split="_")[[1]][3],start=4,stop=4))
  curSums <- getSummaries(curFile)
  if(ff == 1){
    dfAUCROC <- data.frame(n=curN,
                           nDE=curDE,
                           method=curSums$aucROC$method,
                           AUC=curSums$aucROC$maxAUC)
    dfAUCFDR <- data.frame(n=curN,
                           nDE=curDE,
                           method=curSums$aucFDR$method,
                           AUC=curSums$aucFDR$maxAUC)
    dfFDR <- data.frame(n=curN,
                           nDE=curDE,
                           method=curSums$fdr$method,
                           AUC=curSums$fdr$FDR)
  } else if(ff > 1){
    hlpAUCROC <- data.frame(n=curN,
                           nDE=curDE,
                           method=curSums$aucROC$method,
                           AUC=curSums$aucROC$maxAUC)
    dfAUCROC <- rbind(dfAUCROC, hlpAUCROC)
    hlpAUCFDR <- data.frame(n=curN,
                           nDE=curDE,
                           method=curSums$aucFDR$method,
                           AUC=curSums$aucFDR$maxAUC)
    dfAUCFDR <- rbind(dfAUCFDR, hlpAUCFDR)
    hlpFDR <- data.frame(n=curN,
                           nDE=curDE,
                           method=curSums$fdr$method,
                           AUC=curSums$fdr$FDR)
    dfFDR <- rbind(dfFDR, hlpFDR)
  }
}
```


# Visualize performance summaries

```{r, eval=FALSE}
medianMin <- function(x) -median(x)

## AUC under FDR-TPR curve
dfAUCFDR <- dfAUCFDR[!dfAUCFDR$method %in% "RUVs",]
## across all parameters
ggplot(dfAUCFDR, aes(x=reorder(method, AUC, medianMin), y=AUC)) +
  geom_boxplot() 
## facet wrap
ggplot(dfAUCFDR, aes(x=reorder(method, AUC, medianMin), y=AUC)) +
  geom_boxplot() +
  facet_wrap(~ n * nDE, nrow=4, ncol=3) 

## AUC under ROC curve
dfAUCROC <- dfAUCROC[!dfAUCROC$method %in% "RUVs",]
## across all parameters
ggplot(dfAUCROC, aes(x=reorder(method, AUC, medianMin), y=AUC)) +
  geom_boxplot() +
  ylim(c(0.8, 1))
## facet wrap
ggplot(dfAUCROC, aes(x=reorder(method, AUC, medianMin), y=AUC)) +
  geom_boxplot() +
  facet_wrap(~ n * nDE, nrow=4, ncol=3) +
  ylim(c(0.8, 1))

## FDR control
dfFDR <- dfFDR[!dfFDR$method %in% "RUVs",]
## across all parameters
ggplot(dfFDR, aes(x=reorder(method, AUC, medianMin), y=AUC)) +
  geom_boxplot() +
  geom_hline(yintercept=0.05, col="red")
## facet wrap
ggplot(dfFDR, aes(x=reorder(method, AUC, medianMin), y=AUC)) +
  geom_boxplot() +
  facet_wrap(~ n * nDE, nrow=4, ncol=3)  +
  geom_hline(yintercept=0.05, col="red")
```

