---
title: "Murphy 2019 simulation evaluation"
author: "Koen Van den Berge"
date: "3/22/2021"
output: html_document
---

```{r}
library(edgeR) ; library(cqn) ; library(GenomicAlignments)
library(scone)
library(qsmooth)
library(rhdf5)
library(GenomicAlignments)
library(edgeR)
library(UpSetR)
library(rafalib)
library(tidyverse)
library(ggridges)
library(tidyr)
library(quantro)
library(qsmooth)
library(RUVSeq)
library(scone)
library(cqn)
source("../../methods/gcqn_validated.R")
gcqn_qsmooth <- function(counts, gcGroups, bio){
  gcBinNormCounts <- matrix(NA, nrow=nrow(counts), ncol=ncol(counts), dimnames=list(rownames(counts),colnames(counts)))
  for(ii in 1:nlevels(gcGroups)){
    id <- which(gcGroups==levels(gcGroups)[ii])
    countBin <- counts[id,]
    qs <- qsmooth(countBin, group_factor=bio)
    normCountBin <- qs@qsmoothData
    normCountBin <- round(normCountBin)
    normCountBin[normCountBin<0] <- 0
    gcBinNormCounts[id,] <- normCountBin
  }
  return(gcBinNormCounts)
}
source("../../methods/simulation.R")

counts <- read.table("../../data/murphy2019/GSE131625_ATAC-seq_count_table.txt",
                     header=TRUE)
peakRegions <- counts[,1:3]
counts <- round(counts[,-c(1:3)])
```

```{r}
gr <- GRanges(seqnames=gsub(x=peakRegions[,1], pattern="chr", replacement=""), 
              ranges=IRanges(peakRegions[,2], peakRegions[,3]), 
              strand="*")
ff <- FaFile("~/data/genomes/mouse/Mus_musculus.GRCm38.dna.primary_assembly.fa")
peakSeqs <- getSeq(x=ff, gr)
gcContentPeaks <- letterFrequency(peakSeqs, "GC",as.prob=TRUE)[,1]
gcGroups <- Hmisc::cut2(gcContentPeaks, g=20)
gcGroups2 <- Hmisc::cut2(gcContentPeaks, cuts=seq(0.2,1,by=0.1))

ct <- factor(unlist(lapply(strsplit(colnames(counts), split="_"), "[[", 1)),
             levels = c("panBC", "onBC", "offBC", "mCone", "sCone", "rod"))
design <- model.matrix(~ct)
```

# Mock comparison

```{r}
bio <- ct
mockGroup <- splitSamples(bio)
table(bio, mockGroup)

keepSamplesMock <- which(!is.na(mockGroup))
countsMock <- counts[,keepSamplesMock]
mockGroup <- mockGroup[keepSamplesMock]
```

```{r}
mockEvalRes <- mockEvaluation(simCounts = countsMock,
                               grpSim = mockGroup,
                               simGC = gcContentPeaks,
                               simWidth = width(gr),
                               grSim = gr)
```

# Simulate data to add signal

```{r}
signalRes <- signalEvaluation(counts = countsMock,
                              grp = mockGroup,
                               gc = gcContentPeaks,
                               gr = gr,
                               nTotal = 12)
simData <- signalRes$simData
saveRDS(simData, "../../data/simulatedData/murphy2019SimData.rds")
signalRes <- signalRes[-which(names(signalRes) %in% "simData")]
```


# Gather all results

```{r}
resultList <- list(mockEvalRes, signalRes)
saveRDS(resultList, file="../../objects/murphy2019_simulationResults.rds")
```


# Session info

```{r}
sessionInfo()
```


