---
title: "Philip 2017 simulation evaluation"
author: "Koen Van den Berge"
date: "3/22/2021"
output: html_document
---

# Read data, explore GC on count

```{r}
library(edgeR) ; library(cqn) ; library(GenomicAlignments)
library(scone)
library(qsmooth)
library(rhdf5)
library(GenomicAlignments)
library(edgeR)
library(UpSetR)
library(rafalib)
library(tidyverse)
library(ggridges)
library(tidyr)
library(quantro)
library(qsmooth)
library(RUVSeq)
library(scone)
library(cqn)
source("../../methods/gcqn_validated.R")
gcqn_qsmooth <- function(counts, gcGroups, bio){
  gcBinNormCounts <- matrix(NA, nrow=nrow(counts), ncol=ncol(counts), dimnames=list(rownames(counts),colnames(counts)))
  for(ii in 1:nlevels(gcGroups)){
    id <- which(gcGroups==levels(gcGroups)[ii])
    countBin <- counts[id,]
    qs <- qsmooth(countBin, group_factor=bio)
    normCountBin <- qs@qsmoothData
    normCountBin <- round(normCountBin)
    normCountBin[normCountBin<0] <- 0
    gcBinNormCounts[id,] <- normCountBin
  }
  return(gcBinNormCounts)
}
source("../../methods/simulation.R")


files <- list.files("../../data/philip2017_GSE89308/data", full=TRUE)
countsAll <- sapply(files, function(x) read.delim(x), simplify=FALSE)

counts1 <- countsAll[[1]]
regionsAllGR <- GRanges(seqnames=unlist(lapply(strsplit(as.character(counts1$chr),split="chr"), function(x) x[2])), ranges=IRanges(counts1$start, counts1$end), strand="*", mcols=data.frame(symbol=counts1$symbol, counts=counts1$N1))
ff <- FaFile("~/data/genomes/mouse/Mus_musculus.GRCm38.dna.primary_assembly.fa")
peakSeqs <- getSeq(x=ff, regionsAllGR)
gcContentPeaks <- letterFrequency(peakSeqs, "GC",as.prob=TRUE)[,1]
gcGroups <- Hmisc::cut2(gcContentPeaks, g=20)


humanSamples <- 48:length(countsAll)
mouseSamples <- 1:41

countsMouse <- do.call(cbind,lapply(countsAll[mouseSamples], function(x) x[,7]))
colnames(countsMouse) <- unlist(lapply(strsplit(unlist(lapply(strsplit(names(countsAll[mouseSamples]), split="/"),"[[",6)),split="_"), function(x) paste(x[1:3],collapse="_")))
rownames(countsMouse) <- mcols(regionsAllGR)$mcols.symbol
```

## Grid search to approximate DESeq2 size factors, obtain raw counts

```{r}
grid=seq(0.1,3,by=0.001)

# getDis <- function(counts, sf){
#   countsBackTrans <- counts*sf #backtransform division
#   dis <- sqrt(sum((countsBackTrans-round(countsBackTrans))^2))
#   return(dis)
# }

# sf <- vector()
# isMin1 <- vector()
# for(i in 1:ncol(countsMouse)){
#   hlp=countsMouse[,i]
#   distVec <- sapply(grid, function(x) getDis(counts=hlp, sf=x))
#   plot(x=grid, y=distVec, type="l")
#   sf[i] <- grid[which.min(distVec)]
#   normHlp <- hlp*sf[i]
#   isMin1[i] <- round(min(normHlp[!normHlp==0]))==1 # if this is not true the size factor is incorrect because it was too large/low.
#   j <- 1
#   while(!isMin1[i]){
#     j <- j+1
#     o <- base::order(distVec)
#     sf[i] <- grid[o[j]]
#     normHlp <- hlp*sf[i]
#     isMin1[i] <- round(min(normHlp[!normHlp==0]))==1 # if this is not true the size factor is incorrect because it was too large/low.
#   }
# }
# 
# hist(sf,breaks=20)
# saveRDS(sf,file="~/data/atac/philip2017_GSE89308/sf.rds")
sf <- readRDS("../../data/philip2017_GSE89308/sf.rds")

countsMouse <- t(t(countsMouse)*sf)
condition <- unlist(lapply(strsplit(colnames(countsMouse),split="_"),"[[",3))
# fix condition vector
condition[condition%in%paste0("N",1:3)]="N"
condition[condition%in%paste0("M",1:3)]="M"
condition <- factor(condition)

counts <- round(countsMouse)
rownames(counts) <- paste0("peak",1:nrow(counts)) # avoid duplicates
gr <- regionsAllGR
```


# Mock comparison


```{r}
bio <- condition
mockGroup <- splitSamples(bio)
table(bio, mockGroup)

keepSamplesMock <- which(!is.na(mockGroup))
countsMock <- counts[,keepSamplesMock]
mockGroup <- mockGroup[keepSamplesMock]

mockEvalRes <- mockEvaluation(simCounts = countsMock,
                               grpSim = mockGroup,
                               simGC = gcContentPeaks,
                               simWidth = width(gr),
                               grSim = gr)
```




# Simulate data to add signal

```{r}
signalRes <- signalEvaluation(counts = countsMock,
                              grp = mockGroup,
                               gc = gcContentPeaks,
                               gr = gr,
                               nTotal = 12)
```


# Gather all results

```{r}
resultList <- list(mockEvalRes, signalRes)
saveRDS(resultList, file="../../objects/philip2017_simulationResults.rds")
```


# Session info

```{r}
sessionInfo()
```

