---
title: "Benchmark normalization"
author: "Koen Van den Berge"
date: "28 February 2019"
output: html_document
---

# Read in peak counts and get GC content

```{r}
library(GenomicAlignments)
library(scone)
library(cqn)
library(qsmooth)
library(rhdf5)

df <- read.csv("../../data/geschwind2018_GSE95023/GSE95023_readswithinpeaks.csv.gz")
counts <- df[,-c(1:3)]
gr <- GRanges(seqnames=df$CHR, ranges=IRanges(df$START, df$END), strand="*", mcols=counts)
ff <- FaFile("~/data/genomes/human/Homo_sapiens.GRCh37.75.dna_sm.primary_assembly.fa")
peakSeqs <- getSeq(x=ff, gr)
gcContentPeaks <- letterFrequency(peakSeqs, "GC",as.prob=TRUE)[,1]
gcGroups <- Hmisc::cut2(gcContentPeaks, g=20)
```

# Design

Samples are derived from three individual donors.
For every donor, neural progenitor (GZ) zone and neuron rich region (CP) is sequenced.
For every sample, three to four technical replicates are available.

```{r}
patient <- factor(c(rep("A",7), rep("B",6), rep("C",6)))
region <- factor(c(rep("GZ",4), rep("CP",3), rep("GZ",3), rep("CP",3), rep("GZ",3), rep("CP",3)))
```



```{r}
bpparam <- BiocParallel::bpparam()
bpparam$workers <- 1
source("../../methods/scone_evaluation.R")
hk <- readRDS("../../objects/hkListHumanGenomicRanges.rds")
qh <- queryHits(findOverlaps(gr, hk, type="within"))
negcon <- rownames(counts)[qh]
length(negcon)
bio <- region 
## samples for each patient were prepared and sequenced together => batch = patient effect
batch <- patient

# note that cqn_length gives a 'singular design matrix' error.
gcContentScone <- gcContentPeaks
gcGroupsScone <- gcGroups
# different number of bins
gcGroupsScone10 <- Hmisc::cut2(gcContentPeaks, g=10)
gcGroupsScone50 <- Hmisc::cut2(gcContentPeaks, g=50)
gcGroupsScone100 <- Hmisc::cut2(gcContentPeaks, g=100)
h5File <- "/Users/koenvandenberge/tmp/normCounts_geschwind2018.h5"
sconeFit <- sconeEvaluation(counts=counts, bio=bio, negcon=negcon, batch=batch, 
                gcContent=gcContentPeaks, gcGroups=gcGroups, k_ruv=5,
                k_qc=0, adjust_bio='no', eval_kclust = nlevels(bio),
                diffLength=TRUE, bpparam=bpparam, return_norm="hdf5",
                hdf5file=h5File)
saveRDS(sconeFit, "~/Dropbox/research/atacseq/bulk/analysis/benchmarkNormalization/geschwind2018_sconeFit.rds")

## add GC-bias through RLE to scores
rleGC_med <- rleGCh5(h5File = h5File, 
                  gcContent = gcContentScone,
                  type="med")
rleGC_iqr <- rleGCh5(h5File = h5File, 
                  gcContent = gcContentScone,
                  type="iqr")
scores <- get_scores(sconeFit)
# negative is good.
scores <- cbind(scores, 
                rleGC_med = -rleGC_med[rownames(scores)],
                rleGC_iqr = -rleGC_iqr[rownames(scores)])
## recalculate score ranks with new metric
scoreT <- t(scores)
ranked_scores <- apply(scoreT,1,rank)
mean_score_rank <- rowMeans(ranked_scores)
mean_score_rank <- mean_score_rank[order(mean_score_rank, decreasing=TRUE)]
mean_score_rank
```


# Biplot

```{r}
pc_obj <- prcomp(apply(scoreT,1,rank),
                center = TRUE,scale = FALSE)
methodLabelsTmp <- strsplit(rownames(pc_obj$x), split=",")
methodNames <- unlist(lapply(methodLabelsTmp, function(x){
  paste0(x[2:3], collapse=",")
}))
methods <- unlist(lapply(strsplit(methodNames, split=","), "[[", 1))
ruvs <- unlist(lapply(strsplit(methodNames, split=","), function(x) strsplit(x[2],split="_")))[seq(2,length(methodNames)*2, by=2)]
methodNames <- paste(methods,ruvs, sep = "_")

bp_obj <- biplot_color(pc_obj,y = -mean_score_rank,expand = .6, cex=2)
text(x=bp_obj[,1], y=bp_obj[,2], labels=methodNames, cex=2/3)
```


```{r}
file.remove(h5File)
saveRDS(scores, file="~/Dropbox/research/atacseq/bulk/analysis/benchmarkNormalization/geschwind2018_scores.rds")
sessionInfo()
```



