---
title: "Philips 2017 normalization benchmark"
author: "Koen Van den Berge"
date: "25 May 2018"
output: html_document
---

# Read data, explore GC on count

```{r}
library(rafalib)
library(GenomicAlignments)
library(cqn)
library(scone)
library(qsmooth)
library(rhdf5)


files <- list.files("../../data/philip2017_GSE89308/data", full=TRUE)
countsAll <- sapply(files, function(x) read.delim(x), simplify=FALSE)

counts1 <- countsAll[[1]]
regionsAllGR <- GRanges(seqnames=unlist(lapply(strsplit(as.character(counts1$chr),split="chr"), function(x) x[2])), ranges=IRanges(counts1$start, counts1$end), strand="*", mcols=data.frame(symbol=counts1$symbol, counts=counts1$N1))
ff <- FaFile("~/data/genomes/mouse/Mus_musculus.GRCm38.dna.primary_assembly.fa")
peakSeqs <- getSeq(x=ff, regionsAllGR)
gcContentPeaks <- letterFrequency(peakSeqs, "GC",as.prob=TRUE)[,1]
gcGroups <- Hmisc::cut2(gcContentPeaks, g=20)


humanSamples <- 48:length(countsAll)
mouseSamples <- 1:41

countsMouse <- do.call(cbind,lapply(countsAll[mouseSamples], function(x) x[,7]))
colnames(countsMouse) <- unlist(lapply(strsplit(unlist(lapply(strsplit(names(countsAll[mouseSamples]), split="/"),"[[",6)),split="_"), function(x) paste(x[1:3],collapse="_")))
rownames(countsMouse) <- mcols(regionsAllGR)$mcols.symbol
```

## Grid search to approximate DESeq2 size factors, obtain raw counts

```{r}
grid=seq(0.1,3,by=0.001)

# getDis <- function(counts, sf){
#   countsBackTrans <- counts*sf #backtransform division
#   dis <- sqrt(sum((countsBackTrans-round(countsBackTrans))^2))
#   return(dis)
# }

# sf <- vector()
# isMin1 <- vector()
# for(i in 1:ncol(countsMouse)){
#   hlp=countsMouse[,i]
#   distVec <- sapply(grid, function(x) getDis(counts=hlp, sf=x))
#   plot(x=grid, y=distVec, type="l")
#   sf[i] <- grid[which.min(distVec)]
#   normHlp <- hlp*sf[i]
#   isMin1[i] <- round(min(normHlp[!normHlp==0]))==1 # if this is not true the size factor is incorrect because it was too large/low.
#   j <- 1
#   while(!isMin1[i]){
#     j <- j+1
#     o <- base::order(distVec)
#     sf[i] <- grid[o[j]]
#     normHlp <- hlp*sf[i]
#     isMin1[i] <- round(min(normHlp[!normHlp==0]))==1 # if this is not true the size factor is incorrect because it was too large/low.
#   }
# }
# 
# hist(sf,breaks=20)
# saveRDS(sf,file="~/data/atac/philip2017_GSE89308/sf.rds")
sf <- readRDS("../../data/philip2017_GSE89308/sf.rds")

countsMouse <- t(t(countsMouse)*sf)
condition <- unlist(lapply(strsplit(colnames(countsMouse),split="_"),"[[",3))
# fix condition vector
condition[condition%in%paste0("N",1:3)]="N"
condition[condition%in%paste0("M",1:3)]="M"
condition <- factor(condition)
```

# Evaluate normalization procedures

```{r}
bpparam <- BiocParallel::bpparam()
bpparam$workers <- 1
source("../../methods/scone_evaluation.R")
hk <- readRDS("../../objects/hkListMouseGenomicRanges.rds")
qh <- queryHits(findOverlaps(regionsAllGR, hk, type="within"))
negcon <- rownames(countsMouse)[qh]
length(negcon)
bio <- condition
counts <- countsMouse
gr <- regionsAllGR

gcContentScone <- gcContentPeaks
gcGroupsScone <- gcGroups
gcGroupsScone10 <- Hmisc::cut2(gcContentPeaks, g=10)
gcGroupsScone50 <- Hmisc::cut2(gcContentPeaks, g=50)
gcGroupsScone100 <- Hmisc::cut2(gcContentPeaks, g=100)
h5File <- "/Users/koenvandenberge/tmp/normCounts_philip2017.h5"
sconeFit <- sconeEvaluation(counts=counts, bio=bio, negcon=negcon,
                gcContent=gcContentPeaks, gcGroups=gcGroups, k_ruv=5,
                k_qc=0, adjust_bio='no', eval_kclust = nlevels(bio),
                diffLength=TRUE, bpparam=bpparam, return_norm="hdf5",
                hdf5file=h5File)
saveRDS(sconeFit, "~/Dropbox/research/atacseq/bulk/analysis/benchmarkNormalization/philip2017_sconeFit.rds")

## add GC-bias through RLE to scores
rleGC_med <- rleGCh5(h5File = h5File, 
                  gcContent = gcContentScone,
                  type="med")
rleGC_iqr <- rleGCh5(h5File = h5File, 
                  gcContent = gcContentScone,
                  type="iqr")
scores <- get_scores(sconeFit)
scores <- cbind(scores, 
                rleGC_med = -rleGC_med[rownames(scores)],
                rleGC_iqr = -rleGC_iqr[rownames(scores)])
scoreT <- t(scores)
ranked_scores <- apply(scoreT,1,rank)
mean_score_rank <- rowMeans(ranked_scores)
mean_score_rank <- mean_score_rank[order(mean_score_rank, decreasing=TRUE)]
mean_score_rank
```

# Biplot

```{r}
pc_obj <- prcomp(apply(scoreT,1,rank),
                center = TRUE,scale = FALSE)
methodLabelsTmp <- strsplit(rownames(pc_obj$x), split=",")
methodNames <- unlist(lapply(methodLabelsTmp, function(x){
  paste0(x[2:3], collapse=",")
}))
methods <- unlist(lapply(strsplit(methodNames, split=","), "[[", 1))
ruvs <- unlist(lapply(strsplit(methodNames, split=","), function(x) strsplit(x[2],split="_")))[seq(2,length(methodNames)*2, by=2)]
methodNames <- paste(methods,ruvs, sep = "_")

bp_obj <- biplot_color(pc_obj,y = -mean_score_rank,expand = .6, cex=2)
text(x=bp_obj[,1], y=bp_obj[,2], labels=methodNames, cex=2/3)
```

```{r}
file.remove(h5File)
saveRDS(scores, file="~/Dropbox/research/atacseq/bulk/analysis/benchmarkNormalization/philip2017_scores.rds")
sessionInfo()
```


