---
title: "Liu 2019 ATAC-seq mouse tissue atlas normalization benchmark"
author: "Koen Van den Berge"
date: "11/27/2019"
output: html_document
---


```{r}
library(GenomicAlignments)
library(edgeR)
library(UpSetR)
library(rafalib)
library(tidyverse)
library(ggridges)
library(tidyr)
library(quantro)
library(qsmooth)
library(RUVSeq)
library(scone)
library(rhdf5)


counts <- read.table("../../data/liu2019_atlas/ATACseq_Matrix/chromatin.accessibility.raw.count.txt", header=TRUE, stringsAsFactors = FALSE)

```

```{r}
peakNames <- as.character(counts[,1])
peakNamesSplit <- strsplit(peakNames, split="_")
# remove peaks in random chromosomes
rmPeaks <- which(lapply(peakNamesSplit, length) == 4)
counts <- counts[-rmPeaks,]
peakNamesSplit <- peakNamesSplit[-rmPeaks]
sn <- unlist(lapply(peakNamesSplit, "[[", 1))
sn <- substr(sn, 4, nchar(sn))
start <- as.numeric(unlist(lapply(peakNamesSplit, "[[", 2)))
end <- as.numeric(unlist(lapply(peakNamesSplit, "[[", 3)))
gr <- GRanges(seqnames=sn, ranges = IRanges(start=start, end=end), strand="*")
names(gr) <- paste0("peak", 1:length(gr))


# get GC content
ff <- FaFile("~/data/genomes/mouse/Mus_musculus.NCBIM37.67.dna.toplevel.fa")
peakSeqs <- getSeq(x=ff, gr)
gcContentPeaks <- letterFrequency(peakSeqs, "GC",as.prob=TRUE)[,1]
gcGroups <- Hmisc::cut2(gcContentPeaks, g=20)
mcols(gr)$gc <- gcContentPeaks

# remove peak ranges
counts <- counts[,-1]
# restrict to samples discussed in paper
counts <- counts[,!substr(colnames(counts),1,2) == "D0"]

# design
gender <- factor(unlist(lapply(strsplit(colnames(counts), split="_"), "[[", 1)))
tissue <- factor(unlist(lapply(strsplit(colnames(counts), split="_"), "[[", 2)))

# metadata
meta <- openxlsx::read.xlsx("../../data/liu2019_atlas/Metadata.xlsx")
meta <- meta[-nrow(meta),]
metaNames <- paste(meta$Gender, gsub(x=meta$Tissue, pattern=" ", replacement="_"), paste0("Rep",meta$Replicate), sep = "_") # same format as sample names
# same order as count matrix
meta <- meta[match(colnames(counts), metaNames),]

```

```{r}
bpparam <- BiocParallel::bpparam()
bpparam$workers <- 1

source("../../methods/scone_evaluation.R")

expr <- as.matrix(counts)
bio <- droplevels(interaction(gender,tissue))
hk <- readRDS("../../objects/hkListMouseGenomicRanges.rds")
# get peaks that are within hk
qh <- queryHits(findOverlaps(gr, hk, type="within"))
negcon <- rownames(counts)[qh]
batch <- factor(meta$Slide_Lane.of.Sequencer)
qc <- data.frame(meta$chrM.Reads, meta$Percentage.of.Usable.Reads, meta$TSS.Enrichment, meta$IDR.Peaks)

gcContentScone <- gcContentPeaks
gcGroupsScone <- gcGroups
gcGroupsScone10 <- Hmisc::cut2(gcContentPeaks, g=10)
gcGroupsScone50 <- Hmisc::cut2(gcContentPeaks, g=50)
gcGroupsScone100 <- Hmisc::cut2(gcContentPeaks, g=100)
h5File <- "/Users/koenvandenberge/tmp/normCounts_liu2019.h5"
sconeFit <- sconeEvaluation(counts=counts, bio=bio, batch=batch, qc=qc,
                            negcon=negcon, gcContent=gcContentPeaks, 
                            gcGroups=gcGroups, k_ruv=5, k_qc=2, 
                            adjust_bio='no', eval_kclust = nlevels(bio),
                            diffLength=TRUE, bpparam=bpparam, return_norm="hdf5",
                            hdf5file=h5File)

## add GC-bias through RLE to scores
rleGC_med <- rleGCh5(h5File = h5File, 
                  gcContent = gcContentScone,
                  type="med")
rleGC_iqr <- rleGCh5(h5File = h5File, 
                  gcContent = gcContentScone,
                  type="iqr")
scores <- get_scores(sconeFit)
scores <- cbind(scores, 
                rleGC_med = -rleGC_med[rownames(scores)],
                rleGC_iqr = -rleGC_iqr[rownames(scores)])
scoreT <- t(scores)
ranked_scores <- apply(scoreT,1,rank)
mean_score_rank <- rowMeans(ranked_scores)
mean_score_rank <- mean_score_rank[order(mean_score_rank, decreasing=TRUE)]
mean_score_rank

```

# Biplot

```{r}
pc_obj <- prcomp(apply(scoreT,1,rank),
                center = TRUE,scale = FALSE)
methodLabelsTmp <- strsplit(rownames(pc_obj$x), split=",")
methodNames <- unlist(lapply(methodLabelsTmp, function(x){
  paste0(x[2:3], collapse=",")
}))
methods <- unlist(lapply(strsplit(methodNames, split=","), "[[", 1))
ruvs <- unlist(lapply(strsplit(methodNames, split=","), function(x) strsplit(x[2],split="_")))[seq(2,length(methodNames)*2, by=2)]
methodNames <- paste(methods,ruvs, sep = "_")

bp_obj <- biplot_color(pc_obj,y = -mean_score_rank,expand = .6, cex=2)
text(x=bp_obj[,1], y=bp_obj[,2], labels=methodNames, cex=2/3)
```


```{r}
file.remove(h5File)
saveRDS(scores, file="~/Dropbox/research/atacseq/bulk/analysis/benchmarkNormalization/liu2019_scores.rds")
sessionInfo()
```

